repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: DevSecOps Syntax Check
        stages: [pre-push]
        args: [--count, "--select=E9,F63,F7,F82", --show-source, --statistics]
      - id: run-pytest
        name: Run Pytest before Push
        entry: python -m pytest
        language: system
        pass_filenames: false
        stages: [ pre-push ]